title: My blog
description: My personal note of all things I learned that I feared my brain would give up on one day
theme: just-the-docs

url: https://Mustardburger.github.io/myblog

math: mathjax

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
